#!/bin/bash

iDIR="$HOME/.config/hypr/mako/icons"

# Get Volume
get_volume() {
	volume=$(pamixer --get-volume)
	echo "$volume"
}


# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Volume : $(get_volume) %"
	# -i "$(get_icon)"
}

# Increase Volume
inc_volume() {
	pamixer -i 5 && notify_user
}

# Decrease Volume
dec_volume() {
	pamixer -d 5 && notify_user
}

# Toggle Mute
toggle_mute() {
	if [ "$(pamixer --get-mute)" == "false" ]; then
		pamixer -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low  "Volume Switched OFF"
		# -i "$iDIR/volume-mute.png"
	elif [ "$(pamixer --get-mute)" == "true" ]; then
		pamixer -u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Volume Switched ON"
		# -i "$(get_icon)"
	fi
}

# Toggle Mic
toggle_mic() {
	if [ "$(pamixer --default-source --get-mute)" == "false" ]; then
		pamixer --default-source -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Microphone Switched OFF"
		# -i "$iDIR/microphone-mute.png"
	elif [ "$(pamixer --default-source --get-mute)" == "true" ]; then
		pamixer -u --default-source u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Microphone Switched ON"
		#  -i "$iDIR/microphone.png"
	fi
}
# Get icons
# get_mic_icon() {
# 	current=$(pamixer --default-source --get-volume)
# 	if [[ "$current" -eq "0" ]]; then
# 		echo "$iDIR/microphone.png"
# 	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
# 		echo "$iDIR/microphone.png"
# 	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
# 		echo "$iDIR/microphone.png"
# 	elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
# 		echo "$iDIR/microphone.png"
# 	fi
# }

# Notify
notify_mic_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Mic-Level : $(pamixer --default-source --get-volume) %"
	# -i "$(get_mic_icon)"
}

# Increase MIC Volume
inc_mic_volume() {
	pamixer --default-source -i 5 && notify_mic_user
}

# Decrease MIC Volume
dec_mic_volume() {
	pamixer --default-source -d 5 && notify_mic_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
	toggle_mic
elif [[ "$1" == "--get-icon" ]]; then
	get_icon
elif [[ "$1" == "--get-mic-icon" ]]; then
	get_mic_icon
elif [[ "$1" == "--mic-inc" ]]; then
	inc_mic_volume
elif [[ "$1" == "--mic-dec" ]]; then
	dec_mic_volume
else
	get_volume
fi
